sudo: false
language: node_js
node_js: node
before_script:
  - npm run http-server &
  - sleep 2
script: npm run eslint && npm run saucelabs
addons:
  sauce_connect: true
dist: xenial
services:
  - xvfb
